/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'johan' at '23.01.17 19:34' with Gradle 2.14.1
 *
 * @author johan, @date 23.01.17 19:34
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
